[project]
name = "ansible-8"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ansible>=8.0.0,<9.0.0",
    "ansible-lint>=6.8.7",
    "ansible-navigator>=3.4.1",
    "yamllint>=1.37.1",
]
